### ISSUE TITLE
is there embedding gate?

### ISSUE THREAD

**Issue by Hagazzusa** [cshaowang/NetAb#1]
i saw embedding gate image in your paper. but i can't find implementation of gate. is there gate?

**Comment by Hagazzusa** [comment]
sorry. my mistake. i understood gate is neural net module. but it's false, now i know it's selection sequence.

**Comment by cshaowang** [comment]
Thanks for your query. The Gate unit is to perform a selection process where it selects the sentences whose resulting sentiment label (after trained Ab-network) equals to the input label. The selected sentences are then used to train A-network.

**Comment by Hagazzusa** [comment]
> Thanks for your query. The Gate unit is to perform a selection process where it selects the sentences whose resulting sentiment label (after trained Ab-network) equals to the input label. The selected sentences are then used to train A-network.

thanks for your answer. good research to apply. :)
